#!/usr/bin/env python
import subprocess
import tempfile


with tempfile.NamedTemporaryFile(mode="w", suffix=".png") as f:
    ret = subprocess.call([
        "scrot",
        "-s",
        f.name,
    ])
    assert ret == 0
    ret = subprocess.call([
        "convert",
        f.name,
        "-crop",
        "+2+2",
        f.name,
    ])
    assert ret == 0
    ret = subprocess.call([
        "xclip",
        "-selection",
        "clipboard",
        "-t",
        "image/png",
        "-i",
        f.name,
    ])
    assert ret == 0
